### ISSUE TITLE
start ibc

### ISSUE THREAD

**Issue by Nimingez** [google-research/ibc#24]
Hi,thank you for your work. when I run ./ibc/run_tests.sh  
it tell me **Traceback (most recent call last):
  File "/home/nmz/ibc/data/dataset_test.py", line 25, in <module>
    from ibc.environments.block_pushing import block_pushing  # pylint: disable=unused-import
  File "/home/nmz/ibc/environments/block_pushing/block_pushing.py", line 935, in <module>
    if 'BlockPush-v0' in registration.registry.env_specs:
AttributeError: 'dict' object has no attribute 'env_specs'
ERROR: 'PYTHONPATH=/opt/ros/noetic/lib/python3/dist-packages:/home/nmz/ibc/.. python3 /home/nmz/ibc/data/dataset_test.py --alsologtostderr' failed!
**
I just follow you steps!

**Comment by wangyan-hlab** [comment]
@Nimingez 
Hi, I met the same error. Have you resolved it?
